
/********************************************************************
 *                          AUTO-GENERATED                          *
 * This file was auto generated by AccessorsGenerator and is mainly *
 * used to optimize value type get and set operations for a faster  *
 * access to that values. Any changes to this file may be           *
 * overwritten by a subsequent generation process.                  *
********************************************************************/

namespace Postica.BindingSystem.Accessors.Generated
{
    //[AutoGenerated(typeof(AccessorsGenerator))]
    static class SpecializedAccessors_Assembly_Tests
    {
        [UnityEngine.RuntimeInitializeOnLoadMethod(UnityEngine.RuntimeInitializeLoadType.AfterAssembliesLoaded)]
        static void RegisterAccessors()
        {
            // AccessorsFactory.RegisterAccessors(
            //     // --------  Registering Type Postica.BindingSystem.DummyObject -------- /
            //     (typeof(Postica.BindingSystem.DummyObject), "publicFloat", new ObjectTypeAccessor<Postica.BindingSystem.DummyObject, System.Single>(DummyObject_Get_publicFloat, DummyObject_Set_publicFloat)),
            //     (typeof(Postica.BindingSystem.DummyObject), "publicColor", new ObjectTypeAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Color>(DummyObject_Get_publicColor, DummyObject_Set_publicColor)),
            //     (typeof(Postica.BindingSystem.DummyObject), "publicVector", new ObjectTypeAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Vector3>(DummyObject_Get_publicVector, DummyObject_Set_publicVector)),
            //     // --------  Registering Type Postica.BindingSystem.DummyObject.InnerStruct -------- /
            //     (typeof(Postica.BindingSystem.DummyObject.InnerStruct), "transform", new ValueTypeAccessor<Postica.BindingSystem.DummyObject.InnerStruct, UnityEngine.Transform>(InnerStruct_Get_transform, InnerStruct_Set_transform)),
            //     (typeof(Postica.BindingSystem.DummyObject.InnerStruct), "str", new ValueTypeAccessor<Postica.BindingSystem.DummyObject.InnerStruct, System.String>(InnerStruct_Get_str, InnerStruct_Set_str)),
            //     // --------  Registering Type Postica.BindingSystem.DummyObject.InnerClass -------- /
            //     (typeof(Postica.BindingSystem.DummyObject.InnerClass), "transform", new ObjectTypeAccessor<Postica.BindingSystem.DummyObject.InnerClass, UnityEngine.Transform>(InnerClass_Get_transform, InnerClass_Set_transform)),
            //     (typeof(Postica.BindingSystem.DummyObject.InnerClass), "str", new ObjectTypeAccessor<Postica.BindingSystem.DummyObject.InnerClass, System.String>(InnerClass_Get_str, InnerClass_Set_str)));
        }

        /**************************  Start of Postica.BindingSystem.DummyObject **************************/
        // --------  Definitions for: Postica.BindingSystem.DummyObject.publicFloat --------/
        static System.Single DummyObject_Get_publicFloat(in Postica.BindingSystem.DummyObject target) => target.publicFloat;
        static void DummyObject_Set_publicFloat(Postica.BindingSystem.DummyObject target, in System.Single value) => target.publicFloat = value;
        // --------  Definitions for: Postica.BindingSystem.DummyObject.publicColor --------/
        static UnityEngine.Color DummyObject_Get_publicColor(in Postica.BindingSystem.DummyObject target) => target.publicColor;
        static void DummyObject_Set_publicColor(Postica.BindingSystem.DummyObject target, in UnityEngine.Color value) => target.publicColor = value;
        // --------  Definitions for: Postica.BindingSystem.DummyObject.publicVector --------/
        static UnityEngine.Vector3 DummyObject_Get_publicVector(in Postica.BindingSystem.DummyObject target) => target.publicVector;
        static void DummyObject_Set_publicVector(Postica.BindingSystem.DummyObject target, in UnityEngine.Vector3 value) => target.publicVector = value;
        /**************************  End of Postica.BindingSystem.DummyObject **************************/

        /**************************  Start of Postica.BindingSystem.DummyObject.InnerStruct **************************/
        // --------  Definitions for: Postica.BindingSystem.DummyObject.InnerStruct.transform --------/
        static UnityEngine.Transform InnerStruct_Get_transform(in Postica.BindingSystem.DummyObject.InnerStruct target) => target.transform;
        static void InnerStruct_Set_transform(ref Postica.BindingSystem.DummyObject.InnerStruct target, in UnityEngine.Transform value) => target.transform = value;
        // --------  Definitions for: Postica.BindingSystem.DummyObject.InnerStruct.str --------/
        static System.String InnerStruct_Get_str(in Postica.BindingSystem.DummyObject.InnerStruct target) => target.str;
        static void InnerStruct_Set_str(ref Postica.BindingSystem.DummyObject.InnerStruct target, in System.String value) => target.str = value;
        /**************************  End of Postica.BindingSystem.DummyObject.InnerStruct **************************/

        /**************************  Start of Postica.BindingSystem.DummyObject.InnerClass **************************/
        // --------  Definitions for: Postica.BindingSystem.DummyObject.InnerClass.transform --------/
        static UnityEngine.Transform InnerClass_Get_transform(in Postica.BindingSystem.DummyObject.InnerClass target) => target.transform;
        static void InnerClass_Set_transform(Postica.BindingSystem.DummyObject.InnerClass target, in UnityEngine.Transform value) => target.transform = value;
        // --------  Definitions for: Postica.BindingSystem.DummyObject.InnerClass.str --------/
        static System.String InnerClass_Get_str(in Postica.BindingSystem.DummyObject.InnerClass target) => target.str;
        static void InnerClass_Set_str(Postica.BindingSystem.DummyObject.InnerClass target, in System.String value) => target.str = value;
        /**************************  End of Postica.BindingSystem.DummyObject.InnerClass **************************/

        [UnityEngine.Scripting.Preserve]
        static void AOT_Accessors()
        {
            new CompoundAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Vector3>(null);
            new CompoundAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Vector2>(null);
            new CompoundAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Color>(null);
            new PropertyObjectTypeAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Vector3>(null);
            new PropertyObjectTypeAccessor<Postica.BindingSystem.DummyObject, System.Single>(null);
            new CompoundAccessor<Postica.BindingSystem.DummyObject, System.Int32>(null);
            new CompoundAccessor<Postica.BindingSystem.DummyObject, System.Single>(null);
            new PropertyObjectTypeAccessor<Postica.BindingSystem.DummyObject, System.Int32>(null);
            new WrapConcurrentAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Vector3>(null);
            new PropertyValueTypeAccessor<UnityEngine.Vector3, UnityEngine.Vector3>(null);
            new WrapConcurrentAccessor<UnityEngine.Vector3, UnityEngine.Vector3>(null);
            new PropertyObjectTypeAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Color>(null);
            new WrapConcurrentAccessor<Postica.BindingSystem.DummyObject, UnityEngine.Color>(null);
            new PropertyValueTypeAccessor<UnityEngine.Color, UnityEngine.Color>(null);
            new WrapConcurrentAccessor<UnityEngine.Color, UnityEngine.Color>(null);
            new PropertyObjectTypeAccessor<Postica.BindingSystem.DummyObject, Postica.BindingSystem.DummyObject.InnerStruct>(null);
            new WrapConcurrentAccessor<Postica.BindingSystem.DummyObject, Postica.BindingSystem.DummyObject.InnerStruct>(null);
            new PropertyValueTypeAccessor<Postica.BindingSystem.DummyObject.InnerStruct, UnityEngine.Vector2>(null);
        }
    }
}
